### ISSUE TITLE
KeyError: 'email' in resolvenames.py

### ISSUE THREAD

**Issue by zombietango** [swimlane/pyews#10]
In Python 3.7.6 (at least, didn't try with other versions), the .format() call when building the initial SOAP payload fails to properly assign the placeholder {email}. The code uses a name based placeholder while the values passed to format() uses positional placement. Change line 80 in resolvenames.py to 

`'''.format(email=self.userconfiguration.credentials.email_address)`

or change line 76 to 

`<UnresolvedEntry>{}</UnresolvedEntry>`

I'd submit a pull request, but I'm terrible with them :)

**Comment by joshswimlane** [comment]
Fixed this - sorry for the delay!
