### ISSUE TITLE
Only 1 rule is shown

### ISSUE THREAD

**Issue by pkrtaylor** [swimlane/pyews#11]
So i have a problem where only the rule at the top is printed out when i use the GetInboxRules function . How can i solve this where it prints out all the rules?
Also is there a way to get both unhidden and hidden rules. I know in the microsoft exchange documentation they have "Includehidden" as a parameter you can include. Does pyews have this feature?
this is what i have. 

```
from pyews import UserConfiguration, GetSearchableMailboxes, SearchMailboxes, GetInboxRules


userconfig = UserConfiguration('my_email','password')

inboxRules = GetInboxRules('my_email', userconfig).response

print(inboxRules)


```

**Comment by joshswimlane** [comment]
Hello @pkrtaylor thanks for reaching out.  I was able to fix the first issue (my apologies on that).  I will push an updated version of py-ews soon.

The second question is interesting and I believe I have figured out how to add this functionality but if I pushed a branch would you be willing to test this?

Thanks,

**Comment by pkrtaylor** [comment]
Thank you for responding back. Can I ask when will it be pushed?  

Second, I would definitely be willing to test it.
