### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pkrtaylor** [swimlane/pyews#13]
After you fixed the issue where only one rule showed up, I updated the getinboxrules.py file with the changes you made. I started to get this error. It gives me a NoneType error which im pretty sure means that there is no data to output.. I have rules though on my account. Is this a problem on my end?
This is the code i have written.
```
from pyews import UserConfiguration, GetSearchableMailboxes, SearchMailboxes, GetInboxRules


userconfig = UserConfiguration('email','password')

inboxRules = GetInboxRules('pierce@hacwareinc.onmicrosoft.com', userconfig).response

print(inboxRules)

```

Here is the error message from terminal
```
Traceback (most recent call last):
  File "hidden_rules.py", line 7, in <module>
    inboxRules = GetInboxRules('email', userconfig).response
  File "/opt/anaconda3/lib/python3.7/site-packages/pyews/service/getinboxrules.py", line 41, in __init__
    self.response = self.raw_soap
  File "/opt/anaconda3/lib/python3.7/site-packages/pyews/service/getinboxrules.py", line 84, in response
    return_list.append(self.__process_rule_properties(item))
  File "/opt/anaconda3/lib/python3.7/site-packages/pyews/service/getinboxrules.py", line 56, in __process_rule_properties
    for action in item.find('Actions'):
TypeError: 'NoneType' object is not iterable

```

**Comment by joshswimlane** [comment]
Sorry about that - I assumed that there were `Actions` properties on all inbox rules but I'm guess not.

In your new `getinboxrules.py` can you replace the method `def __process_rule_properties` with this:

```
def __process_rule_properties(self, item):
        if item:
            return_dict = {}
            for prop in item:
                if prop.name != 'Conditions' and prop.name != 'Actions':
                    if prop.name not in return_dict:
                        return_dict[prop.name] = prop.string
            if item.find('Conditions'):
                for condition in item.find('Conditions'):
                    if 'conditions' not in return_dict:
                        return_dict['conditions'] = []
                    return_dict['conditions'].append({
                        condition.name: condition.string
                    })
            if item.find('Actions'):
                for action in item.find('Actions'):
                    if 'actions' not in return_dict:
                        return_dict['actions'] = []
                    return_dict['actions'].append({
                        action.name: action.string
                    })
            return return_dict
```

let me know if this fixed it or not

**Comment by pkrtaylor** [comment]
Ok so a couple things. The fix above works. After I changed source code, the inbox rules all printed out. It took me a while to test the hidden rule feature because actually adding a hidden rule was a little tricky for me. I finally got it and it gives me an error. One thing to keep in mind though, when i have the hidden rule parameter as false it prints all the unhidden rules, but when I put it as True, thats when it gives me an error. 

this is the error it gives me 

```
Traceback (most recent call last):
  File "hidden_rules.py", line 7, in <module>
    inboxRules = GetInboxRules('email', userconfig, hidden_rules=True).response
  File "/Users/Pierce/Library/Python/2.7/lib/python/site-packages/pyews/service/getinboxrules.py", line 44, in __init__
    self.response = self.raw_soap
  File "/Users/Pierce/Library/Python/2.7/lib/python/site-packages/pyews/service/getinboxrules.py", line 92, in response
    return_list.append(FindHiddenInboxRules(self.userconfiguration).response)
  File "/Users/Pierce/Library/Python/2.7/lib/python/site-packages/pyews/service/findhiddeninboxrules.py", line 41, in __init__
    self.response = self.raw_soap
  File "/Users/Pierce/Library/Python/2.7/lib/python/site-packages/pyews/service/findhiddeninboxrules.py", line 82, in response
    for item in value.find('InboxRules'):
TypeError: 'NoneType' object is not iterable

```

**Comment by joshswimlane** [comment]
@pkrtaylor Thanks for the feedback!  Can you share how or what process you did to create the hidden inbox rules?  I want to recreate it in my environment.

In your opinion, do you want it to return all hidden and unhidden rules when set to `True` or just the hidden rules when set to `True` and if false (default) it will return all unhidden rules?  Just curious of the best usability.

**Comment by pkrtaylor** [comment]
The way i did it was using MFCMAPI. This can only be used on a windows os.
I downloaded it from here https://github.com/stephenegriffin/mfcmapi/releases/tag/20.0.20307.01
I downloaded the MFCMAPI.x64.exe.20.0.20307.01.zip version
Make sure you have the outlook web app on your computer.
After you have downloaded mfcampi click on the MFCMapi application. 
The way i did it was i went into office 365 first. 
clicked on the outlook mail icon 
when it asked me to sign in, directly below it gives you an option to sign in manually. 
I clicked that, then it showed me a number of icons, i clicked the exchange icon to sign in. 
After i followed the guide below.

Here is a link to the guide that I followed. 
https://cybersecthreat.com/detect-hidden-inbox-forward-rule-in-on-premise-exchange/


I think it would be good print just the hidden rules when set to true.

**Comment by MSAdministrator** [comment]
@pkrtaylor 

I wanted to share that there is a new dev version of py-ews which should resolve this and many other issues:

I have a new development verson of pyews that I would like you to try.

`pip install py-ews-dev==3.1.0`

Once it is installed then create a new Python script file.

Inside that file paste this:

```
from pyews import EWS

ews = EWS(
    'email@company.com,
    'some_password'
)

for item in ews.search_and_delete_message('phish', what_if=True):
    print(item)
```

You should see logs on your console and that is expected. Please let me know how this works for you.
