### ISSUE TITLE
Question on Design with regards to EWS API

### ISSUE THREAD

**Issue by rtkaratekid** [swimlane/pyews#23]
Hi pyews! I'm reviewing this library in anticipation with use within swimlane. I'm unfamiliar with .NET and Microsoft APIs, so reading the code here has been really educational in how at least the exchange server works. I've got a few questions about the code.

---

The first question has to do with the endpoint classes. Each of them refer to ```T_NAMESPACE``` or ```M_NAMESPACE``` with objects that are not explicitly created in the code. An example is in `getsearchablemailboxes.py`
```python
self.search_filter = self.M_NAMESPACE.SearchFilter(search_filter) if search_filter else self.M_NAMESPACE.SearchFilter()
```
I **think** that the `SearchFilter` field in `M_NAMESPACE` gets created in `base.py` when you use `ElementMaker`. But I've tried following the URLs in that file to understand what the microsoft schema is, but each link shows as invalid. Am I missing something in this logic?

---

My next question is just a clarifying one. So the workflow for this library is that you establish an EWS connection with a username/email and the associated password. But to establish the connection you first reach out to `Autodiscover` endpoints (defined in `endpoints.py`) to try and find out where the correct Exchange server is correct? Once you've found it, how do you know what URLs to contact for the various API calls? I've been reading the MS docs and have only seen reference to how to contact the server via their C# classes and am left a little confused about what the actual endpoints and requests look like. It seems that they **really** want you to use the C# and aren't keen to disclose the actual web details of what is required.

Thanks for the work on this library and I look forward to your responses!

**Comment by rtkaratekid** [comment]
Oh geez I think I misunderstood the SOAP API principle. It looks like you just send all of the API calls to the same URL but you just change the XML body to detail what you want done.
It seems you can view the endpoints/behaviors in the .NET documentation to understand what you want done and then check out the [XML Guide](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/ews-xml-elements-in-exchange) to see how it's done with XML instead of C#.

I assume that the answer to my first question is still that those namespaces are created within the XML document that you're using in your SOAP requests.

**Comment by MSAdministrator** [comment]
Sorry for the late reply @rtkaratekid but I’m actually off on vacation so it may be a bit before I can respond more thoroughly.

**Comment by rtkaratekid** [comment]
@MSAdministrator enjoy it! I just like to post follow-ups for documentation purposes. I look forward to your eventual response though.

**Comment by rtkaratekid** [comment]
Just a friendly bump

**Comment by MSAdministrator** [comment]
@rtkaratekid Sorry for the delay here. I will try and answer your questions here:

1. The `T_NAMESPACE` and other namespace properties are actually defined in the base.py class (https://github.com/swimlane/pyews/blob/master/pyews/service/base.py#L34). This class is inherited by both the `Operation` class and the `Autodiscover` class.  Depending on the endpoint (e.g. GetSearchableMailboxes or GetDomainSettings for example) you could have different namespaces (e.g. Autodiscover has A_NAMESPACE).
2. This documentation may help understand these namespaces and how they convert to XML: https://github.com/swimlane/pyews/blob/master/docs/service/add_additional_service_endpoints.md
3. As far as the workflow of connecting to Exchange, we first attempt to connect to each endpoint and once we have a 200 response then we know this root endpoint is correct and were successful to authenticate.  Your realization is correct BTW. All SOAP requests are POST requests to a URL with the XML Body formatted for the request type you are wanting/sending.

I hope this help answers your questions and If I missed anything or you have any additional questions please let me know! You can also check this out and it may help as well: https://swimlane.com/blog/understanding-apis-soap
